Car_Rental/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Car_Rental.Models
{
    [Table("location")]
    public class Location
    {
        [Key, Column(Order = 0)]
        [ForeignKey("Client")]
        public int id_client { get; set; }
        public Client Client { get; set; }

        [Key, Column(Order = 1)]
        [ForeignKey("Voiture")]
        public int Id_voiture { get; set; }
        public Voiture Voiture { get; set; }

        [Required]
        public string type_location { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime date_debut { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime date_fin { get; set; }

        public double prix_location_total { get; set; }
        public string Etat_location { get; set; }
    }
}

Car_Rental/Areas/Admin/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Car_Rental.Models;

namespace Car_Rental.Areas.Admin.Controllers
{
    public class LocationsController : Controller
    {
        private LocationContext db = new LocationContext();

        // GET: Admin/Locations
        public ActionResult Index()
        {
            var locations = db.Locations.Include(l => l.Client).Include(l => l.Voiture);
            return View(locations.ToList());
        }

        // GET: Admin/Locations/Delete/5
        public ActionResult Delete(int? idC, int? idV)
        {
            if (idC == null || idV == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(idC, idV);
            if (location == null)
            {
                return HttpNotFound();
            }
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ValidateReservation()
        {

            int? idC = int.Parse(Request["id_client"]);
            int? idV = int.Parse(Request["id_voiture"]);


            if (idC == null || idV == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var location = db.Locations.Find(idC, idV);
            if (location == null)
            {
                return HttpNotFound();
            }
            //
            location.Etat_location = "Validé";

            db.Entry(location).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Car_Rental/Areas/Admin/Views/Locations/Index.cshtml
@model IEnumerable<Car_Rental.Models.Location>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h4>Liste des locations:</h4>
<hr />

<table class="table table-bordered">
    <tr class="bg-light">
        <th>
            Nom du client
        </th>
        <th>
            Image du véhicule
        </th>
        <th>
            Type de location
        </th>
        <th>
            Date de debut
        </th>
        <th>
            Date de fin
        </th>
        <th>
            Montant total
        </th>
        <th>
            Etat de location
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="bg-white">
            <td>
                @Html.DisplayFor(modelItem => item.Client.Nom_complet)
            </td>
            <td>
                <img src="@Url.Content("~/Content/Images/"+@item.Voiture.Image)" alt="@Html.DisplayFor(modelItem => item.Voiture.Type_carburant)" width="120" height="80">
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.type_location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date_debut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date_fin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prix_location_total) Dhs
            </td>
            <td>
                <span class="@(item.Etat_location == "En attente" ? "badge badge-warning" : "badge badge-success")" style="font-size:13px">
                    @Html.DisplayFor(modelItem => item.Etat_location)

                </span>

            </td>
            <td>
                <div class="d-flex justify-content-between">
                    <a href="@Url.Action("Delete", "Locations",new { idC = item.id_client, idV = item.Id_voiture })"
                       class="btn btn-danger btn-sm"
                       onclick="return confirm('Êtes-vous sûr? ')">
                        <i class="fas fa-trash"></i>
                    </a>

                    @if (item.Etat_location == "En attente")
                    {
                        using (Html.BeginForm("ValidateReservation", "Locations", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <input type="hidden" name="id_client" id="id_client" value="@item.id_client" />
                            <input type="hidden" name="id_voiture" id="id_voiture" value="@item.Id_voiture" />
                            <button type="submit" class="btn btn-success btn-sm">
                                <i class="fas fa-check"></i>
                            </button>
                        }
                    }
                </div>

            </td>
        </tr>
    }

</table>