Car_Rental/Areas/Admin/Controllers/CatégorieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Car_Rental.Models;

namespace Car_Rental.Areas.Admin.Controllers
{
    public class CatégorieController : Controller
    {
        private LocationContext db = new LocationContext();

        // GET: Admin/Catégorie
        public ActionResult Index()
        {
            return View(db.Catégories.ToList());
        }

        // GET: Admin/Catégorie/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Catégorie catégorie = db.Catégories.Find(id);
            if (catégorie == null)
            {
                return HttpNotFound();
            }
            return View(catégorie);
        }

        // GET: Admin/Catégorie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Catégorie/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_categorie,Nom")] Catégorie catégorie)
        {
            if (ModelState.IsValid)
            {
                db.Catégories.Add(catégorie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(catégorie);
        }

        // GET: Admin/Catégorie/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Catégorie catégorie = db.Catégories.Find(id);
            if (catégorie == null)
            {
                return HttpNotFound();
            }
            return View(catégorie);
        }

        // POST: Admin/Catégorie/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_categorie,Nom")] Catégorie catégorie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(catégorie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(catégorie);
        }

        // GET: Admin/Catégorie/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Catégorie catégorie = db.Catégories.Find(id);
            if (catégorie == null)
            {
                return HttpNotFound();
            }
            db.Catégories.Remove(catégorie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Admin/Catégorie/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Catégorie catégorie = db.Catégories.Find(id);
        //    db.Catégories.Remove(catégorie);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Car_Rental/Areas/Admin/Controllers/ModèleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Car_Rental.Models;

namespace Car_Rental.Areas.Admin.Controllers
{
    public class ModèleController : Controller
    {
        private LocationContext db = new LocationContext();

        // GET: Admin/Modèle
        public ActionResult Index()
        {
            return View(db.Modèles.ToList());
        }

        // GET: Admin/Modèle/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modèle modèle = db.Modèles.Find(id);
            if (modèle == null)
            {
                return HttpNotFound();
            }
            return View(modèle);
        }

        // GET: Admin/Modèle/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Modèle/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_modele,Marque,Serie")] Modèle modèle)
        {
            if (ModelState.IsValid)
            {
                db.Modèles.Add(modèle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(modèle);
        }

        // GET: Admin/Modèle/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modèle modèle = db.Modèles.Find(id);
            if (modèle == null)
            {
                return HttpNotFound();
            }
            return View(modèle);
        }

        // POST: Admin/Modèle/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_modele,Marque,Serie")] Modèle modèle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(modèle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(modèle);
        }

        // GET: Admin/Modèle/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modèle modèle = db.Modèles.Find(id);
            if (modèle == null)
            {
                return HttpNotFound();
            }
            db.Modèles.Remove(modèle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Admin/Modèle/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Modèle modèle = db.Modèles.Find(id);
        //    db.Modèles.Remove(modèle);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Car_Rental/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Car_Rental.Models;

namespace Car_Rental.Areas.Admin.Controllers
{
    public class UsersController : Controller
    {
        private LocationContext db = new LocationContext();

        // GET: Admin/Users
        public ActionResult Index()
        {
            if (!((bool)Session["is_admin"]))
            {
                return RedirectToAction("Forbidden", "../Admin");
            }
            return View(db.Clients.ToList());
        }

        // GET: Admin/Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Admin/Users/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_client,Nom_complet,Date_naissance,Telephone,Adresse_mail,Mots_de_passe,Image_cin,Image_permis,Etat_compte,isAdmin")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Admin/Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_client,Nom_complet,Date_naissance,Telephone,Adresse_mail,Mots_de_passe,Image_cin,Image_permis,Etat_compte,isAdmin")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Admin/Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ValidateAccount()
        {
            int? id = int.Parse(Request["id_client"]);


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }

            client.Etat_compte = "Validé";
            db.Entry(client).State = EntityState.Modified;

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Car_Rental/Areas/Admin/Controllers/VoituresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Car_Rental.Models;

namespace Car_Rental.Areas.Admin.Controllers
{
    public class VoituresController : Controller
    {
        private LocationContext db = new LocationContext();

        // GET: Admin/Voitures
        public ActionResult Index()
        {
            var voitures = db.Voitures.Include(v => v.Catégorie).Include(v => v.Modèle);
            if (!((bool)Session["is_admin"]))
            {
                return RedirectToAction("Forbidden", "../Admin");
            }
            return View(voitures.ToList());
        }

        // GET: Admin/Voitures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voiture voiture = db.Voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            return View(voiture);
        }

        // GET: Admin/Voitures/Create
        public ActionResult Create()
        {
            ViewBag.Id_categorie = new SelectList(db.Catégories, "Id_categorie", "Nom");
            ViewBag.Id_modele = new SelectList(db.Modèles, "Id_modele", "Marque");
            return View();
        }

        // POST: Admin/Voitures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_voiture,Image,Date_mise_en_circulation,Type_carburant,Prix_location,Id_categorie,Id_modele")] Voiture voiture)
        {
            if (ModelState.IsValid)
            {
                db.Voitures.Add(voiture);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_categorie = new SelectList(db.Catégories, "Id_categorie", "Nom", voiture.Id_categorie);
            ViewBag.Id_modele = new SelectList(db.Modèles, "Id_modele", "Marque", voiture.Id_modele);
            return View(voiture);
        }

        // GET: Admin/Voitures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voiture voiture = db.Voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_categorie = new SelectList(db.Catégories, "Id_categorie", "Nom", voiture.Id_categorie);
            ViewBag.Id_modele = new SelectList(db.Modèles, "Id_modele", "Marque", voiture.Id_modele);
            return View(voiture);
        }

        // POST: Admin/Voitures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_voiture,Image,Date_mise_en_circulation,Type_carburant,Prix_location,Id_categorie,Id_modele")] Voiture voiture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(voiture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_categorie = new SelectList(db.Catégories, "Id_categorie", "Nom", voiture.Id_categorie);
            ViewBag.Id_modele = new SelectList(db.Modèles, "Id_modele", "Marque", voiture.Id_modele);
            return View(voiture);
        }

        // GET: Admin/Voitures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voiture voiture = db.Voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            db.Voitures.Remove(voiture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Admin/Voitures/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Voiture voiture = db.Voitures.Find(id);
        //    db.Voitures.Remove(voiture);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Car_Rental/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.6.1/materia/bootstrap.min.css" integrity="sha512-pT2nPljr3bMBfzrib2bICuziqGd9faZ/99ZQj4orbFOwnktSLbqcaAeU3u4jffzywAehove7/dLN3RT668m03g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous" />
    @*<link href="~/Content/Css/profile_dropdown.css" rel="stylesheet" />*@
    <link href="~/Content/Css/spur.css" rel="stylesheet" />


</head>
<body>
    <div class="dash">

        <div class="dash-nav dash-nav-dark">
            <header>
                <a href="" class="menu-toggle">
                    <i class="fas fa-bars"></i>
                </a>
                <a href="" class="spur-logo"><i class="fas fa-car"></i> <span>Car<span style="color: #FFD105 ">Rent</span></span></a>
            </header>
            <nav class="dash-nav-list">

                <a href="@Url.Action("Index", "Dashboard")" class="dash-nav-item">
                    <i class="fas fa-home"></i> Dashboard
                </a>

                <a href="@Url.Action("Index", "Locations")" class="dash-nav-item">
                    <i class="fas fa-arrow-circle-down"></i> Réservations
                </a>

                <a href="@Url.Action("Index", "Users")" class="dash-nav-item">
                    <i class="fas fa-user"></i> Utilisateurs
                </a>

                <a href="@Url.Action("Index", "Voitures")" class="dash-nav-item">
                    <i class="fas fa-car-side"></i> Véhicules
                </a>


                <a href="@Url.Action("Index", "Catégorie")" class="dash-nav-item">
                    <i class="fas fa-square"></i> Catégories
                </a>

                <a href="@Url.Action("Index", "Modèle")" class="dash-nav-item">
                    <i class="fas fa-circle"></i> Modèles
                </a>

                <a href="@Url.Action("Index", "../Home")" class="dash-nav-item">
                    <i class="fas fa-arrow-left"></i> Retour au site web
                </a>
            </nav>
        </div>
        <!---->
        <!---->

        <header class="dash-toolbar">
            <a href="#" class="menu-toggle">
                <i class="fas fa-bars"></i>
            </a>
            <a href="#" class="searchbox-toggle">
                <i class="fas fa-search"></i>
            </a>
            @if (Session["id_client"] != null)
            {
            <div class="tools">

                <div class="dropdown tools-item">
                    <a href="#" class="" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                        @Html.ActionLink("Se déconnecter", "../../Accounts/Logout", null, new { @class = "dropdown-item" })
                    </div>
                </div>
            </div>
            }
        </header>
        <div class="dash-app">

            <main class="dash-content">
                <div class=" body-content">
                    @RenderBody()

                </div>
            </main>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>

    <script src="~/Scripts/spur.js"></script>

    @RenderSection("Scripts", required: false)


</body>
</html>

Car_Rental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.6.1/materia/bootstrap.min.css" integrity="sha512-pT2nPljr3bMBfzrib2bICuziqGd9faZ/99ZQj4orbFOwnktSLbqcaAeU3u4jffzywAehove7/dLN3RT668m03g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous" />
    <link href="~/Content/Css/profile_dropdown.css" rel="stylesheet" />
    <link href="~/Content/Css/spur.css" rel="stylesheet" />

    <style>
        .btn-voiture {
            background: #FFD105;
        }

            .btn-voiture:hover {
                background: #ffffff;
            }

        .card:hover {
            box-shadow: 0 0 0 1px #FFD105;
        }

        .card-img-top {
            width: 100%;
            height: 21vw;
            object-fit: cover;
        }

        #footer {
            border-top: 4px solid #FFD105;
            padding: 30px;
        }
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="font-size: 15px; font-weight: bold; border-bottom: 5px solid #FFD105">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"> <i class="fas fa-car"></i> Car<span style="color: #FFD105 ">Rent</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Acceuil", "../Home/Index", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Nos véhicules", "../Voitures/Index", null, new { @class = "nav-link" })
                    </li>
                </ul>
                @if (Session["id_client"] != null)
                {
                    <div class="dropdown">
                        <button class="btn btn-light d-flex">
                            <span class="my-1">Salut, @Session["nom_client"] </span>
                            <span class="material-icons">
                                expand_more
                            </span>
                        </button>
                        <div class="dropdown-content">
                            @if ((bool)Session["is_admin"] == true)
                            {

                                @Html.ActionLink("DASHBOARD", "Dashboard", "Admin", new { area = "" }, null)
                            }
                            @Html.ActionLink("Mes réservations", "../Voitures/ReservationList")
                            @Html.ActionLink("Se déconnecter", "../Accounts/Logout")
                        </div>

                    </div>
                }
                else
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            @Html.ActionLink("Se connecter", "../Accounts/Login", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Créer un compte", "../Accounts/Signup", null, new { @class = "nav-link" })
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
    <div class=" body-content">
        @RenderBody()

        <footer class="bg-light text-center" id="footer">
            <p>&copy; @DateTime.Now.Year - CarRent</p>
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/spur.js"></script>

    @RenderSection("Scripts", required: false)


</body>
</html>